# ansible-playbook ./vim_setup.yml -K

---
- hosts: localhost
  connection: local
  vars:
    vim_related_packages: ['vim',
                           'vim-addon-manager',
                           'vim-common',
                           'vim-gocomplete',
                           'vim-syntax-docker']
    vim_plugin_repos: ['https://github.com/pearofducks/ansible-vim.git',
                       'https://github.com/davidhalter/jedi-vim.git',
                       'https://github.com/Shougo/neocomplcache.vim.git',
                       'https://github.com/Shougo/neocomplete.vim.git',
                       'https://github.com/scrooloose/nerdtree.git',
                       'https://github.com/myusuf3/numbers.vim.git',
                       'https://github.com/vim-airline/vim-airline.git',
#                      'https://github.com/vim-syntastic/syntastic.git', # giving ale a try
                       'https://github.com/morhetz/gruvbox.git',
                       'https://github.com/fatih/vim-go.git',
                       'https://github.com/plasticboy/vim-markdown.git',
                       'git://github.com/tpope/vim-endwise.git',
                       'https://github.com/w0rp/ale.git',
                       'git://github.com/tpope/vim-surround.git',
                       'git://github.com/godlygeek/tabular.git',
                       ]

  pre_tasks:

  - name: downloading vimrc
    get_url:
      url: https://raw.githubusercontent.com/dimitrios-work/vi/master/.vimrc
      dest: "~/.vimrc"
      mode: 0644
      force: yes

  - name: creating the necessary vim directory structure for the user
    file:
      path: "~/{{ item }}"
      state: directory
      mode: 0755
    with_items:
      - '.vim'
      - '.vim/autoload'
      - '.vim/bundle'

  - name: downloading yaml.vim
    get_url:
      dest: "~/.vim/yaml.vim"
      url: https://raw.githubusercontent.com/dimitrios-work/vi/master/.vim/yaml.vim
      mode: 0644
      force: yes

  - name: downloading pathogen
    get_url:
      url: https://raw.githubusercontent.com/tpope/vim-pathogen/master/autoload/pathogen.vim
      dest: "~/.vim/autoload/pathogen.vim"
      mode: 0644
      force: yes

  - name: updating apt cache
    apt:
      update_cache: yes
    become: True
    become_method: sudo

  tasks:

  - name: installing vim and related packages
    apt:
      name: "{{ item }}"
      state: latest
    become: True
    become_method: sudo
    with_items:
      - "{{ vim_related_packages }}"

  - name: installing vim plugins
    git:
      repo: "{{ item }}"
      dest: '~/.vim/bundle/{{ item | basename | replace(".git", "")}}'
    with_items:
      - "{{ vim_plugin_repos }}"
